name: Default
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@master
        with:
          fetch-depth: 100

      - name: Build
        run: make -C production/ package

      - name: Release
        run: cd production/release && ls -l
