name: Default
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build
        run: make -C production/ package

      - name: Release
        uses: Roang-zero1/github-upload-release-artifacts-action@master
        with:
          args:
            - production/release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
