name: Master
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build
        run: make -C production/ package

      - name: Release
        uses: actions/upload-artifact@v1
        with:
          name: telco-obeznik # double zipping issue: https://github.com/actions/upload-artifact/issues/39
          path: production/release/telco-obeznik.zip

      - name: Deploy to Staging
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          ftp-server: ftp://stagingtelcobeznik.chytrak.cz/
          ftp-username: stagingtelcobeznik.chytrak.cz
          ftp-password: ${{ secrets.FTP_PASSWORD }}
          local-dir: www
          git-ftp-args: "--insecure --dry-run"
