name: Python Tests
on: [push]
jobs:
  unittests:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare repository
        uses: actions/checkout@master
      - name: Run Unittest
        run: python3 -m unittest tests/**/*.py
